Login page
execom-eu/exebite pull request #153
Opened 2020-09-07 13:02 UTC by abericExecom

Refactored login page

2020-09-08 12:46 UTC, BraneOpacic21 requested changes
Good 👍

2020-09-08 12:46 UTC, BraneOpacic21 commented on client-app/angular.json
> +    "analytics": "8d4be075-be15-4e0f-bad4-2d9f1ab8ba90"
Why are we adding analytics to the project? 😄

2020-09-08 12:46 UTC, BraneOpacic21 commented on client-app/src/app/components/login/login.component.html
> +      <img src="../../../assets/ExeBite-logo.svg" class="rounded mb-1" alt="Exebite" />
We could do something like this:

https://stackoverflow.com/questions/41506847/how-to-make-an-alias-for-a-long-path-in-angular-cli

P.S.
Adding @mkovacevicExecom and @MiljkovicVeljko to take a look, as well 😄

2020-09-08 12:46 UTC, BraneOpacic21 commented on client-app/src/app/components/login/login.component.html
> +            <img src="../../../assets/google-logo.png" class="google-icon mr-4" alt="Google" />
Same as above ⏫

2020-09-08 12:46 UTC, BraneOpacic21 commented on client-app/src/app/components/login/login.component.html
> +          <button class="btn btn-light rounded-pill mt-5 pl-4 pr-5" (click)="login()">
You may be right, but i'm just wondering - why do we use `pl-4 pr-5` instead of `px`?

2020-09-08 12:58 UTC, abericExecom commented on client-app/src/app/components/login/login.component.html
> +          <button class="btn btn-light rounded-pill mt-5 pl-4 pr-5" (click)="login()">
I needed different value for padding left because of the position of google img inside the button. Should I maybe use px on the button element and use mx for the google image element ?

2020-09-08 13:00 UTC, abericExecom commented on client-app/angular.json
> +    "analytics": "8d4be075-be15-4e0f-bad4-2d9f1ab8ba90"
I don't remember adding that, I will remove it ;)

2020-09-08 13:21 UTC, BraneOpacic21 commented on client-app/angular.json
> +    "analytics": "8d4be075-be15-4e0f-bad4-2d9f1ab8ba90"
good times 😄

2020-09-09 05:32 UTC, abericExecom commented on client-app/src/app/components/login/login.component.html
> +          <button class="btn btn-light rounded-pill mt-5 pl-4 pr-5" (click)="login()">
I tried combining px and mx, i get better result with pl and pr in button element.

2020-09-09 13:02 UTC, BraneOpacic21 commented on client-app/src/app/components/login/login.component.html
> +          <button class="btn btn-light rounded-pill mt-5 pl-4 pr-5" (click)="login()">
Hmm.. I might need to see this, we should have a call on this one 😄

2020-09-09 13:21 UTC, BraneOpacic21 approved these changes

2020-09-09 13:22 UTC, merged