Feature/116 header
execom-eu/exebite pull request #154
Opened 2020-09-08 10:50 UTC by mkovacevicExecom

![image](https://user-images.githubusercontent.com/70578537/92466881-0d311200-f1d1-11ea-86f6-c6411920d2a9.png)
![image](https://user-images.githubusercontent.com/70578537/92466915-19b56a80-f1d1-11ea-9d6b-c415dfb54440.png)

- added ngx toastr for error messages
- added breakpoint, palette, and font scss files
- added a shared folder with folders for components, enums, constants, directives,... 

note: 
In the future we will reorganize the components folder

2020-09-08 13:14 UTC, BraneOpacic21 requested changes
Really good, overall 😄

2020-09-08 13:14 UTC, BraneOpacic21 commented on client-app/src/app/pages/home/header/header.component.scss
> +  justify-content: space-between;
If we are using bootstrap in our project (and I believe we are):

`class="d-flex align-items-center justify-content-between"`

2020-09-08 13:14 UTC, BraneOpacic21 commented on client-app/src/app/pages/home/header/header.component.scss
> +  align-items: center;
Same as above ⏫

2020-09-08 13:14 UTC, BraneOpacic21 commented on client-app/src/app/pages/home/header/header.component.scss
> +  justify-content: center;
Bootstrap classes

2020-09-08 13:14 UTC, BraneOpacic21 commented on client-app/src/app/pages/home/header/header.component.scss
> +    transform: none !important;
This seems like a hack 😸

2020-09-08 13:14 UTC, BraneOpacic21 commented on client-app/src/app/pages/home/header/header.component.scss
> +
Remove empty line

2020-09-08 13:14 UTC, BraneOpacic21 commented on client-app/src/app/pages/home/header/header.component.spec.ts
> +      declarations: [HeaderComponent],
We don't plan using tests - so this file is obsolete. Please remove it.

2020-09-08 13:14 UTC, BraneOpacic21 commented on client-app/src/app/pages/home/header/header.component.ts
> +import { UserService } from 'src/app/services/user.service';
Remove empty lines

2020-09-08 13:14 UTC, BraneOpacic21 commented on client-app/src/app/pages/home/header/header.component.ts
> +  }
This will slide for now, but we should be introducing state management in our app (NgRx)

2020-09-08 13:14 UTC, BraneOpacic21 commented on client-app/src/app/pages/home/home.component.spec.ts
>    beforeEach(() => {
Remove test file, pls

2020-09-08 13:14 UTC, BraneOpacic21 commented on client-app/src/assets/styles/_breakpoint.scss
> +$bp-small: 32rem;
I prefer `px` breakpoints, but that's just my opinion here 🤷

2020-09-08 13:14 UTC, BraneOpacic21 commented on client-app/src/styles.scss
> +
Remove empty line

2020-09-09 06:34 UTC, mkovacevicExecom commented on client-app/src/app/pages/home/header/header.component.scss
> +    transform: none !important;
That was because I needed to change the bootstrap styles, do I need to change that?

2020-09-09 12:23 UTC, BraneOpacic21 commented on client-app/src/app/pages/home/header/header.component.scss
> +    transform: none !important;
If that's the main reason (and you tried other more subtle ways 😄) I'm okay with that 👍

2020-09-09 13:23 UTC, BraneOpacic21 approved these changes

2020-09-10 06:10 UTC, BraneOpacic21 approved these changes

2020-09-10 06:10 UTC, merged