Feature/165 delete comment modal
execom-eu/exebite pull request #172
Opened 2020-09-17 13:18 UTC by mkovacevicExecom

This branch contains task https://github.com/execom-eu/exebite/issues/165
Added NgRX for comments and modal data.
Added breakpoint (1200px), and fix css.

![image](https://user-images.githubusercontent.com/70578537/93475463-eb363e80-f8f8-11ea-9015-ce3f1e17f736.png)

2020-09-18 07:35 UTC, abericExecom commented on client-app/src/app/app-routing.module.ts
> +    // canActivate: [AuthGuard],
Should this be commented ?

2020-09-18 07:42 UTC, abericExecom commented on client-app/src/app/pages/comments/delete-comment/delete-comment.component.ts
> +import * as CommentsActions from '../../../store/actions/comments.actions';
we should maybe have a global path for store

2020-09-18 08:04 UTC, mkovacevicExecom commented on client-app/src/app/pages/comments/delete-comment/delete-comment.component.ts
> +import * as CommentsActions from '../../../store/actions/comments.actions';
we should create a task for it

2020-09-18 08:06 UTC, mkovacevicExecom commented on client-app/src/app/app-routing.module.ts
> +    // canActivate: [AuthGuard],
I fixed that :)

2020-09-18 08:12 UTC, MiljkovicVeljko commented on client-app/src/app/pages/comments/delete-comment/delete-comment.component.scss
> +::ng-deep .modal-content {
Did you try to avoid ng-deep? Try encapsulation: ViewEncapsulation.None, or to override by parent class. If none of those doesn't work, we are doomed to ng-deep. :)

2020-09-18 08:12 UTC, MiljkovicVeljko commented on client-app/src/app/pages/comments/delete-comment/delete-comment.component.scss
> +::ng-deep .modal-open .modal {
The same about ng-deep like as above.

2020-09-18 09:28 UTC, mkovacevicExecom commented on client-app/src/app/pages/comments/delete-comment/delete-comment.component.scss
> +::ng-deep .modal-open .modal {
solved

2020-09-18 09:28 UTC, mkovacevicExecom commented on client-app/src/app/app.component.ts
> +  constructor(private store: Store<{ modal: { isOpen: boolean; data: any; component: string } }>) {}
solved

2020-09-18 09:47 UTC, MiljkovicVeljko approved these changes

2020-09-18 12:55 UTC, BraneOpacic21 requested changes

2020-09-18 12:55 UTC, BraneOpacic21 commented on client-app/src/app/app.component.ts
> +  constructor(private store: Store<ModalState>) {}
Type is wrong here - we should have our `Store<IStore>`

Two things to mention here:
1. We should prefix our interfaces with capital `I` before the name (like I've done above)
2. Our IStore should contain all parts of the store - `IModalState`, `ICommentsState` etc.

2020-09-18 12:55 UTC, BraneOpacic21 commented on client-app/src/app/app.component.ts
> +    this.subscription = this.store.select('modal').subscribe((data) => {
Four points here:
1. Good thing is that you are using a subscription to unsubscribe in `ngOnDestroy`, but the name should be more meaningful - bc we aren't gonna call the second sub `this.subscription2`, are we? 😄 
2.  `.subscribe(({isOpen, type}) => { this.isOpen = isOpen; this.type = type; }`
3. From previous part, `component` suggests that we are sending a component, which is an anti-pattern in Redux/NgRX. However, we aren't sending the `component`, just the `type`  😄 
4. We should introduce the selectors file and `.select()` our state "slices" accordingly

2020-09-18 12:55 UTC, BraneOpacic21 commented on client-app/src/app/pages/comments/comment-card/comment-card.component.ts
> +  constructor(private store: Store<ModalState>) {}
Change store type

2020-09-18 12:55 UTC, BraneOpacic21 commented on client-app/src/app/pages/comments/comment-card/comment-card.component.ts
> +    this.store.dispatch(new ModalActions.OpenModal(this.comment, MODAL.DELETE_COMMENT));
Example of a nicely dispatched action:
![image](https://user-images.githubusercontent.com/45173769/93598374-e044e200-f9bc-11ea-8aaa-2f585301cb0e.png)
P.S.
Find the comment about declaring actions bellow, it will help out with this one 😄

2020-09-18 12:55 UTC, BraneOpacic21 commented on client-app/src/app/pages/comments/comments.component.ts
> +    this.store.dispatch(new CommentsActions.AddComments(COMMENTS));
Same comment as earlier

2020-09-18 12:55 UTC, BraneOpacic21 commented on client-app/src/app/store/actions/comments.actions.ts
> +export type CommentsActions = RemoveComment | AddComments;
Lets use a more modern approach here:

![image](https://user-images.githubusercontent.com/45173769/93598862-9ad4e480-f9bd-11ea-869a-e376b0cc651b.png)

And that way you can dispatch your actions as I described earlier. 🛩️

2020-09-18 12:55 UTC, BraneOpacic21 commented on client-app/src/app/store/actions/modal.actions.ts
> +export type ModalActions = OpenModal | CloseModal;
Same here.

2020-09-18 12:55 UTC, BraneOpacic21 commented on client-app/src/app/store/reducers/comments.reducer.ts
> +        comments: [...action.payload],
This works as intended if ADD_COMMENTS action always resolve into swapping the old state of comments with the new one. If we, however, want to keep the old comments and add new ones, then you should use:
`comments: [...state.comments, ...action.payload]`

2020-09-18 12:55 UTC, BraneOpacic21 commented on client-app/src/app/store/reducers/modal.reducer.ts
> +}
Lets use this instead:

https://ngrx.io/api/store/createReducer

2020-09-18 12:55 UTC, BraneOpacic21 commented on client-app/src/app/pages/comments/comments.component.ts
> +    this.subscription = this.store.select('comments').subscribe((data) => {
Destructure comments in your `subscribe` chained method.
Select your state with a selector file

https://ngrx.io/guide/store/selectors

2020-09-18 12:55 UTC, BraneOpacic21 commented on client-app/src/app/pages/comments/delete-comment/delete-comment.component.ts
> +  }
Same comments as above (and check all the other files on your PR)

2020-09-22 06:28 UTC, BraneOpacic21 requested changes

2020-09-22 06:28 UTC, BraneOpacic21 commented on client-app/src/app/pages/comments/delete-comment/delete-comment.component.ts
> +    this.closeModal();
This is good if we want to close the modal on action dispatch, not action success. So, is this behavior intended? @mkovacevicExecom

2020-09-22 06:28 UTC, BraneOpacic21 commented on client-app/src/app/store/reducers/modal.reducer.ts
> +    type: action.payload.type,
Destructure data and type from `action.payload`, and you don't even have to write it twice afterwards (e.g. `isOpen: true, data, type`)

2020-09-22 06:28 UTC, BraneOpacic21 commented on client-app/src/app/store/selectors/selector.ts
> +export const selectModal = (state: IStore) => state.modal;
Not an issue, but more of a standard: naming should be `getCommentsSelector`, `getModalSelector`
As your app scales, you are going to have more pieces of redux state (e.g. modal, comments, users, loggedUser, refData etc.), and the best practice here is to keep naming in order and correctly slice your redux state and select it like:

![image](https://user-images.githubusercontent.com/45173769/93849941-68710300-fcad-11ea-8f2e-3c2253c77c61.png)

2020-09-22 06:39 UTC, mkovacevicExecom commented on client-app/src/app/pages/comments/delete-comment/delete-comment.component.ts
> +    this.closeModal();
Yes, I wanted to close the modal, if the user successfully deleted the comment. :D is that oke?

2020-09-22 07:23 UTC, BraneOpacic21 approved these changes

2020-09-22 07:23 UTC, BraneOpacic21 commented on client-app/src/app/pages/comments/delete-comment/delete-comment.component.ts
> +    this.closeModal();
> if the user successfully deleted the comment

... meaning, we are waiting for the server response to know is it successful? 🤔 
If so, what happens if the action fails, do we want to keep the modal open and display a flash message about failure or do we want to close it, no matter what?
If its the second case, this is good 👍

2020-09-22 07:27 UTC, mkovacevicExecom commented on client-app/src/app/pages/comments/delete-comment/delete-comment.component.ts
> +    this.closeModal();
My idea was to close the modal anyway, and if action fails user could see toastr message on the screen :D

2020-09-22 07:27 UTC, mkovacevicExecom commented on client-app/src/app/pages/comments/delete-comment/delete-comment.component.ts
> +    this.closeModal();
But maybe it will change when the backend is ready, so we'll see :D

2020-09-22 07:55 UTC, BraneOpacic21 commented on client-app/src/app/pages/comments/delete-comment/delete-comment.component.ts
> +    this.closeModal();
Ok, lets keep it this way 😄

2020-09-22 07:59 UTC, merged