Restaurants header
execom-eu/exebite pull request #178
Opened 2020-09-21 06:54 UTC by MiljkovicVeljko

1. Favourite added
2. Banner added
3. quantity shared component
4. expand added
5. meal card & meal item added
![image](https://user-images.githubusercontent.com/47921421/93739132-d94de780-fbe7-11ea-9908-903c8bf8704b.png)
![image](https://user-images.githubusercontent.com/47921421/93739180-f387c580-fbe7-11ea-97e4-9a1caacfdc98.png)

2020-09-21 08:39 UTC, abericExecom commented on client-app/src/app/shared/components/quantity/quantity.component.html
> +  <span class="quanter mr-4 ml-4">{{ quantity }}</span>
mx-4 maybe ?

2020-09-21 09:25 UTC, mkovacevicExecom commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.html
> +          <img src="../../../../assets/images/{{ star }}.svg" alt="star" />
you should use 'assets/images/{{star}}.svg"

2020-09-21 09:26 UTC, mkovacevicExecom commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.html
> +      <img src="../../../../assets/images/{{ offerBrand }}.svg" alt="special-offers" />
same here

2020-09-21 09:30 UTC, mkovacevicExecom commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.ts
> +      case 'Topli Obrok':
Maybe you should create constants for 'Topli obrok'  :D

2020-09-21 09:30 UTC, mkovacevicExecom commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.ts
> +      case 'Pod Lipom':
same here

2020-09-22 06:42 UTC, BraneOpacic21 requested changes

2020-09-22 06:42 UTC, BraneOpacic21 commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.ts
> +  }
Since we plan to have multiple restaurants, this could be optimized - we could have a helper obj which would hold all of the data you pass to the function (e.g. `{name: '', tooltipType: '', specialOffer: ''}`)

Currently, your method is not really re-usable, since you have to statically type all of the stuff - but, if you keep it in a helper obj, things would fall in place much easier 😄

2020-09-22 06:42 UTC, BraneOpacic21 commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.ts
> +    this.star = this.isFavourite ? 'star' : 'favourite';
Naming something `star` makes little sense if it can resolve to either 'star' or 'favorite' string 😄

2020-09-22 06:42 UTC, BraneOpacic21 commented on client-app/src/app/pages/restaurants-overview/restaurants-carousel/restaurants-carousel.component.html
> +    <ng-template class="owl-item" carouselSlide [id]="item.id + 1" [width]="370">
`[id]="item.id + 1"` 
Carousel doesn't support 0 based [id]s? 🤔

2020-09-22 06:42 UTC, BraneOpacic21 commented on client-app/src/app/pages/restaurants-overview/restaurants-carousel/restaurants-carousel.component.scss
> +  z-index: -11;
⚔️

2020-09-22 06:42 UTC, BraneOpacic21 commented on client-app/src/app/shared/components/quantity/quantity.component.ts
> +  }
I know this is used because you target the `[disabled]` attribute, but calling a method `canDecrease()`, and it resolves to true if `this.quantity === 0` makes no sense 😄 

Adjust the naming, please!

2020-09-22 11:46 UTC, MiljkovicVeljko commented on client-app/src/app/pages/restaurants-overview/restaurants-carousel/restaurants-carousel.component.html
> +    <ng-template class="owl-item" carouselSlide [id]="item.id + 1" [width]="370">
No, that's my mess :D

2020-09-24 12:26 UTC, abericExecom commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-item/meal-item.component.ts
> +  ngOnInit(): void {}
Delete constructor and ngOnInit if not used

2020-09-24 12:27 UTC, abericExecom commented on client-app/src/app/pages/restaurants-overview/restaurants-carousel/restaurants-carousel.component.ts
> +}
Same as above constructor and ng OnInit

2020-09-24 12:28 UTC, abericExecom commented on client-app/src/app/pages/restaurants-overview/restaurants-overview.component.ts
> +  ngOnInit(): void {}
ngOnInit, same as above

2020-09-24 12:29 UTC, abericExecom commented on client-app/src/app/shared/components/quantity/quantity.component.ts
> +  constructor() {}
Delete constructor

2020-09-24 12:29 UTC, abericExecom commented on client-app/src/app/shared/components/quantity/quantity.component.ts
> +  ngOnInit(): void {}
NgOnInit and constructor

2020-09-24 12:32 UTC, abericExecom commented on client-app/src/assets/styles/styles.scss
> +@import 'mixins';
@import 'styles maybe ? '

2020-09-24 13:01 UTC, abericExecom approved these changes

2020-09-25 07:17 UTC, aberonja requested changes
Ja kad krenem da gledam vas PR od 40+ 🤣 

![](https://i.giphy.com/media/MF8H7YGMlwSm4/giphy.webp)

2020-09-25 07:17 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-item/meal-item.component.html
> +      <p class="px-3 text-capitalize">{{ meal.name }}</p>
Is this a paragraph?

2020-09-25 07:17 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-item/meal-item.component.html
> +      <p class="px-3 text-capitalize">{{ meal.name }}</p>
This is not so important here since this is not a public web app, but still, keep SEO in mind.

2020-09-25 07:17 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-item/meal-item.component.html
> +      <p class="meal-details">Lorem ipsum dolor.</p>
?

2020-09-25 07:17 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-item/meal-item.component.html
> +      <p class="mr-3">{{ likes }} {{ 'LIKES' | translate }}</p>
Same as above (SEO comment).

2020-09-25 07:17 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-item/meal-item.component.html
> +      <p>{{ dislikes }} {{ 'DISLIKES' | translate }}</p>
^

2020-09-25 07:17 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-item/meal-item.component.html
> +        <span class="meal-comments">{{ 'COMMENT.COMMENTS' | translate }}</span>
This could be a paragraph probably.

2020-09-25 07:17 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-item/meal-item.component.scss
> +      padding: 1rem 3rem 0 3rem;
shorthand

2020-09-25 07:17 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-item/meal-item.component.scss
> +.cursor-pointer {
This is a shared class, move it into some global.css.

2020-09-25 07:17 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-item/meal-item.component.ts
> +  @Input() meal: any;
`@TODO` or type.

2020-09-25 07:17 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/restaurants-carousel/restaurants-carousel.component.html
> +</owl-carousel-o>
Noice, owl carousel was a good package in jQuery. I didn't know that it exists as an npm package.

2020-09-25 07:17 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/restaurants-carousel/restaurants-carousel.component.scss
> +    margin: 0 3.5rem 0 0.5rem;
shorthand

2020-09-25 07:17 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/restaurants-carousel/restaurants-carousel.component.scss
> +  z-index: -4;
Why?

2020-09-25 07:17 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/restaurants-overview.component.scss
> +  padding: 1rem 0 3rem 0;
shorthand

2020-09-25 07:17 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/restaurants-carousel/restaurants-carousel.component.ts
> +  encapsulation: ViewEncapsulation.None,
Why encapsulation?

2020-09-25 07:17 UTC, aberonja commented on client-app/src/app/shared/components/order-button/order-button.component.scss
> +    padding: 0 1rem 0 4rem;
shorthand

2020-09-25 07:17 UTC, aberonja commented on client-app/src/app/shared/components/tabs/tabs.component.html
>    *ngFor="let tab of tabs"
Please reorder. *ngFor, class, [ngClass], (click).

2020-09-25 07:17 UTC, aberonja commented on client-app/src/assets/i18n/rs.json
> +    "CANCEL": "Otkazi",
ž

2020-09-25 07:27 UTC, mkovacevicExecom commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-item/meal-item.component.html
> +  <div [ngClass]="{ 'bg-grey': add }" class="meal-item d-flex justify-content-between">
ngClass 😀

2020-09-25 07:58 UTC, mkovacevicExecom commented on client-app/src/app/pages/restaurants-overview/restaurants-carousel/restaurants-carousel.component.ts
> +  encapsulation: ViewEncapsulation.None,
That Veljko put to override carousel css, is that okay?

2020-09-25 09:40 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/restaurants-carousel/restaurants-carousel.component.ts
> +  encapsulation: ViewEncapsulation.None,
Hm, if that was needed than ok, but please read more about encapsulation if you hadn't.

2020-09-25 09:49 UTC, mkovacevicExecom commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.html
> +      <p class="text-uppercase">{{ 'FOOD.SOUPS_AND_SIDE_DISHES' | translate }}</p>
fixed

2020-09-25 12:26 UTC, aberonja requested changes

2020-09-25 12:41 UTC, aberonja approved these changes

2020-09-25 12:59 UTC, merged