My account UI
execom-eu/exebite pull request #180
Opened 2020-09-22 05:29 UTC by abericExecom

![my-account-page](https://user-images.githubusercontent.com/69471615/93846775-51c6ae00-fca5-11ea-9773-76a7b7ccebf4.png)

2020-09-22 07:09 UTC, mkovacevicExecom commented on client-app/src/app/shared/components/location-selector/location-selector.component.ts
> +  public locationSetup: Array<IDropdownItem> = LOCATION_SETUP;
maybe you should put this before constructor :)

2020-09-22 07:10 UTC, mkovacevicExecom commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.scss
> +  color: white;
/n

2020-09-22 07:10 UTC, mkovacevicExecom commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.scss
> +  color: white;
you should use $white from pallete.scss

2020-09-22 07:10 UTC, mkovacevicExecom commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.scss
> +    padding: 0;
/n

2020-09-22 07:19 UTC, mkovacevicExecom commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.ts
> +
I think the new line is redundant

2020-09-22 07:21 UTC, mkovacevicExecom commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.ts
> +    this.selectorImg = this.isLocationSelector ? 'assets/images/arrow.svg' : 'assets/images/light-arrow-down.svg';
Maybe you should write something like this in HTML src='assets/images/${image}.svg, and in ts file write image name :D

2020-09-22 07:22 UTC, mkovacevicExecom commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.ts
> +    this.selectedItem.emit(this.currentItem);
Do we need to emit data in ngOnInit, maybe we should set default value :D

2020-09-22 07:32 UTC, mkovacevicExecom commented on client-app/src/app/pages/my-account/table-info/table-info.component.html
> +
remove new line

2020-09-22 07:34 UTC, mkovacevicExecom commented on client-app/src/app/pages/my-account/table-info/table-info.component.ts
> +    if (type === 'myOrders') {
maybe you should use switch case :D

2020-09-22 07:42 UTC, mkovacevicExecom commented on client-app/src/app/pages/my-account/table-info/table-info.component.ts
> +    const ordersArray = orders.map((order) => {
maybe you can destruct order data, (date, meal) => {...}

2020-09-22 07:52 UTC, mkovacevicExecom commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.ts
> +    const filteredItems = this.items.filter((item) => item !== dropdownItem);
hm, maybe you should remove the item depend on the index in array :D

2020-09-22 08:12 UTC, mkovacevicExecom commented on client-app/src/app/shared/setup/my-account-info.setup.ts
> +  ['date', 'Date'],
maybe you should write something like this: 
[ {  
      code: 'date',
      text: 'Date',
 }
]

2020-09-22 08:13 UTC, mkovacevicExecom commented on client-app/src/app/shared/setup/my-account-info.setup.ts
> +export const PAYMENT_INFO_SETUP = [
maybe the name should be PAYMENT_INFO_TABLE_SETUP

2020-09-22 09:18 UTC, abericExecom commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.ts
> +    this.selectedItem.emit(this.currentItem);
For some reason it doesn't work when I don't emit and set default value in table-info component. Let's see what is Brane going to say

2020-09-22 09:48 UTC, mkovacevicExecom commented
remove spec.ts files for table-info component and my-account component :)

2020-09-23 15:06 UTC, mkovacevicExecom approved these changes

2020-09-23 15:06 UTC, mkovacevicExecom commented on client-app/src/app/pages/my-account/my-account.component.ts
> +import { IStore } from 'src/app/store/selectors/selector';
change to@store/selectors...

2020-09-23 15:06 UTC, mkovacevicExecom commented on client-app/src/app/pages/my-account/my-account.component.ts
> +import { SetSelectedType } from 'src/app/store/actions/infoTable.actions';
same here

2020-09-23 15:06 UTC, mkovacevicExecom commented on client-app/src/app/pages/my-account/table-info/table-info.component.ts
> +import { IStore, getTableColumns, getTableData } from 'src/app/store/selectors/selector';
@store/...

2020-09-23 15:07 UTC, mkovacevicExecom commented on client-app/src/app/pages/my-account/my-account.component.html
> +    <h1 class="mt-4"><strong>Hello!</strong></h1>
add translate for hello

2020-09-23 15:07 UTC, mkovacevicExecom commented on client-app/src/app/pages/my-account/my-account.component.html
> +    <p class="user-name mt-5">Your credit balance</p>
translate

2020-09-24 06:20 UTC, mkovacevicExecom commented on client-app/src/app/shared/setup/my-account-info.setup.ts
> +  { id: 1, text: 'My payments', itemName: 'myPayments' },
translate text

2020-09-24 07:21 UTC, aberonja requested changes

2020-09-24 07:21 UTC, aberonja commented on client-app/src/app/store/reducers/infoTable.reducer.ts
> +};
Can this be implicit?

2020-09-24 07:21 UTC, aberonja commented on client-app/src/app/store/reducers/infoTable.reducer.ts
> +};
Same here.

2020-09-24 12:58 UTC, abericExecom commented on client-app/src/app/pages/my-account/my-account.component.scss
> +    width: 12.2rem;
I just used original size

2020-09-24 12:59 UTC, abericExecom commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.html
> +          src="assets/images/{{ selectorImg }}.svg"
It does work

2020-09-24 12:59 UTC, abericExecom commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.scss
> +    width: 30rem;
set min-width instead of this

2020-09-24 13:02 UTC, abericExecom commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.scss
> +    width: 3rem;
Solved Heights with paddings, removed width here

2020-09-24 13:04 UTC, abericExecom commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.scss
> +    width: 8.9rem;
also min-width

2020-09-24 13:52 UTC, abericExecom commented on client-app/src/app/pages/my-account/my-account.component.scss
> +    width: 12.2rem;
And Brane agreed to use rems everywhere, just to be consistent

2020-09-25 07:34 UTC, aberonja requested changes
Just a bit more.

2020-09-25 07:34 UTC, aberonja commented on client-app/src/app/core/models/infoTable-state.ts
> +  tableData: Array<any>;
Leave `@TODO` or type this.

2020-09-25 07:34 UTC, aberonja commented on client-app/src/app/pages/my-account/my-account.component.html
> +    <p class="user-name mt-4">{{ 'ACCOUNT.DEFAULT_LOCATION' | translate }}</p>
This is not a paragraph, change it to span or something that suits you more. Even the SEO is not important please keep it in mind.

2020-09-25 07:34 UTC, aberonja commented on client-app/src/app/pages/my-account/my-account.component.html
> +    <p class="user-name mt-5">{{ 'ACCOUNT.CREDIT_BALANCE' | translate }}</p>
Here as well.

2020-09-25 07:34 UTC, aberonja commented on client-app/src/app/pages/my-account/table-info/table-info.component.ts
> +  public tableColumns: Array<any>;
`@TODO` or type.

2020-09-25 07:34 UTC, aberonja commented on client-app/src/app/pages/my-account/table-info/table-info.component.html
> +<table mat-table [dataSource]="tableData" class="info-table">
Maybe make this `| async`, since you're not doing anything with the data in the `.ts` file. What do you say?

2020-09-25 07:34 UTC, aberonja commented on client-app/src/app/pages/my-account/table-info/table-info.component.ts
> +  }
`| async` as the comment above. Please check if it's better.

2020-09-25 07:34 UTC, aberonja commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.html
> +          src="assets/images/{{ selectorImg }}.svg"
Mkaaay :D

2020-09-25 07:34 UTC, aberonja commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.scss
> +        padding-top: 0.5rem !important;
Is `!important` necessary?

2020-09-25 07:34 UTC, aberonja commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.scss
> +      padding-top: 0 !important;
Same as above.

2020-09-25 07:34 UTC, aberonja commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.ts
> +    this.selectorImg = this.isLocationSelector ? 'white-arrow-down' : 'light-arrow-down';
Could this be on line 16? I'm not sure THB, but I think it can.

2020-09-25 07:34 UTC, aberonja commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.ts
> +    this.currentItem = this.getFirstItemAndRemove(this.items);
Hm, this as well.

2020-09-25 07:34 UTC, aberonja commented on client-app/src/app/store/reducers/infoTable.reducer.ts
> +      return PAYMENT_INFO_TABLE_SETUP;
Since you only have two options I would suggest switching this to if statement. Also, you don't have a default case here.

2020-09-25 07:34 UTC, aberonja commented on client-app/src/app/store/reducers/infoTable.reducer.ts
> +      return getPayments();
Same as above.

2020-09-25 07:34 UTC, aberonja commented on client-app/src/app/store/reducers/infoTable.reducer.ts
> +  return ordersArray;
/n

2020-09-25 07:34 UTC, aberonja commented on client-app/src/assets/i18n/rs.json
> +    "MY_ORDERS": "Moje narudžbine",
Porudžbine ili narudžbine, choose one and stick with it.

2020-09-25 10:24 UTC, abericExecom commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.scss
> +        padding-top: 0.5rem !important;
It is because I'm setting pt-0 in html if the element is just dropdown selector, if it's location selector I need to override that pt-0

2020-09-25 10:24 UTC, abericExecom commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.scss
> +      padding-top: 0 !important;
Similar answer as above

2020-09-25 10:28 UTC, abericExecom commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.ts
> +    this.selectorImg = this.isLocationSelector ? 'white-arrow-down' : 'light-arrow-down';
It cannot because islocationSelector gets default value at that moment which is false

2020-09-25 10:29 UTC, abericExecom commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.ts
> +    this.currentItem = this.getFirstItemAndRemove(this.items);
This also needs to be here similar reason as comment above

2020-09-25 11:20 UTC, aberonja commented on client-app/src/app/pages/my-account/my-account.component.scss
> +    }
Could this be done in a mobile-first manner? if you change the breakpoint to `min-width` and add `top: 7rem;`?

2020-09-25 11:21 UTC, aberonja commented on client-app/src/app/pages/my-account/table-info/table-info.component.ts
> +  public tableData$: Observable<Array<IInfoTableDataOrders | IInfoTableDataPayments>>;
Noice :)

2020-09-25 11:22 UTC, aberonja commented on client-app/src/app/pages/my-account/table-info/table-info.component.ts
> +    this.tableData$ = this.store.select(getTableData);
You don't need ngOnInit for this, this could be added after the line 14 :)

2020-09-25 11:22 UTC, aberonja commented on client-app/src/app/pages/my-account/table-info/table-info.component.ts
> +    this.tableData$ = this.store.select(getTableData);
Do you think it looks better now?

2020-09-25 11:24 UTC, aberonja commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.scss
> +        padding-top: 0.5rem !important;
Hm, could you add ternary `if` in the HTML to solve this issue?

2020-09-25 11:24 UTC, aberonja commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.scss
> +      padding-top: 0 !important;
Same as above :D

2020-09-25 11:26 UTC, aberonja commented on client-app/src/app/store/reducers/infoTable.reducer.ts
> +  } else if (selectedType === AccountInfoTypes.PAYMENTS_TYPE) {
You don't need else here since you have return in the block above.

2020-09-25 11:26 UTC, aberonja commented on client-app/src/app/store/reducers/infoTable.reducer.ts
> +  } else if (selectedType === AccountInfoTypes.PAYMENTS_TYPE) {
Same as above.

2020-09-25 11:27 UTC, aberonja commented on client-app/src/assets/i18n/rs.json
> +    "ORDERS": "Porudžbine",
Here you have porudžbine and 4 rows later narudžbine. Please choose one.

2020-09-25 11:28 UTC, aberonja requested changes
Fix this and we're done :)

2020-09-25 12:38 UTC, aberonja commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.scss
> +        padding-top: 0.5rem !important;
@mkovacevicExecom Take a look at this pls.

2020-09-25 12:41 UTC, aberonja approved these changes

2020-09-25 13:05 UTC, merged