Project setup
execom-eu/exebite pull request #184
Opened 2020-09-23 12:35 UTC by sserbula

2020-09-25 14:13 UTC, nikolicdusan requested changes
Please address the comments before we can proceed with merging

2020-09-25 14:13 UTC, nikolicdusan commented on Exebite.GoogleSheetAPI/Properties/Resources.Designer.cs
>  //------------------------------------------------------------------------------
This is auto-generated file based on its parent .resx file. It should not be modified by hand. Please make sure that you update resources via Managed Resource Editor by double clicking .resx file. You can also right click the .resx file and choose Open With, then find Managed Resource Editor.

2020-09-25 14:13 UTC, nikolicdusan commented on Exebite.API/Controllers/SheetsController.cs
> +                // _apiService.UpdateMainMenuParrilla();
Please avoid pushing commented out code. Also, strive towards fixing the actual issue rather than masking it.

Also, are you sure that the application crash is not specific for your machine only?

2020-09-27 13:22 UTC, sserbula commented on Exebite.GoogleSheetAPI/Properties/Resources.Designer.cs
>  //------------------------------------------------------------------------------
I did everything as you described. Resources.resx is the only file that I edited. As I can see, he only formatted it, but I'm not sure why.

2020-09-27 13:27 UTC, sserbula commented on Exebite.API/Controllers/SheetsController.cs
> +                // _apiService.UpdateMainMenuParrilla();
This bug was addressed to me by Bojan, because I got same the problem when fetching sheets as he did.
Maybe we can create an issue and then investigate further what is an actual problem?

2020-09-28 07:42 UTC, nikolicdusan approved these changes
Looks good!

2020-09-28 07:43 UTC, merged