Account info component
execom-eu/exebite pull request #193
Opened 2020-09-29 12:43 UTC by abericExecom

2020-09-29 12:53 UTC, mkovacevicExecom commented on client-app/src/app/app.module.ts
> +import { customerReducer } from './store/reducers/customer.reducer';
use @store

2020-09-29 12:53 UTC, mkovacevicExecom commented on client-app/src/app/app.module.ts
> +  declarations: [...COMPONENTS, DropdownDirective, ClickOutsideDirective, CurrencyFormatPipe, AccountInfoComponent],
maybe you should move AccountInfoComponent in COMPONENTS list

2020-09-29 12:54 UTC, mkovacevicExecom commented on client-app/src/app/core/models/meal.ts
> +  condiments: string[];
maybe Array<string> for type

2020-09-29 12:55 UTC, mkovacevicExecom commented on client-app/src/app/pages/my-account/account-info/account-info.component.scss
> +    width: 12.2rem;
min-width?

2020-09-29 12:56 UTC, mkovacevicExecom commented on client-app/src/app/pages/my-account/account-info/account-info.component.scss
> +      width: 8rem;
same here

2020-09-29 12:56 UTC, mkovacevicExecom commented on client-app/src/app/pages/my-account/account-info/account-info.component.ts
> +  constructor(private store: Store<IStore>) {}
/n before constructor

2020-09-29 12:57 UTC, mkovacevicExecom commented on client-app/src/app/pages/my-account/my-account.component.scss
>  @import 'styles';
Is this import necessary?

2020-09-29 12:59 UTC, mkovacevicExecom commented on client-app/src/app/store/reducers/customer.reducer.ts
> +    photoUrl: action.payload.photoUrl,
you should use ...action.payload, in that case, you don't need to use  id: action.payload.id...

2020-09-29 13:03 UTC, abericExecom commented on client-app/src/app/pages/my-account/account-info/account-info.component.scss
> +    width: 12.2rem;
Its an Image, Beki said you don't min-width, the content is not changing.

2020-09-29 13:03 UTC, abericExecom commented on client-app/src/app/pages/my-account/account-info/account-info.component.scss
> +      width: 8rem;
Same as above

2020-09-29 13:03 UTC, mkovacevicExecom commented on client-app/src/app/store/reducers/customer.reducer.ts
> +);
maybe you should add a user remove action, we will need it when logging out?

2020-09-29 13:05 UTC, abericExecom commented on client-app/src/app/pages/my-account/my-account.component.scss
>  @import 'styles';
Yes, I'm using breakpoints

2020-09-29 13:07 UTC, abericExecom commented on client-app/src/app/store/reducers/customer.reducer.ts
> +    photoUrl: action.payload.photoUrl,
Uuuu, i like that :D

2020-09-29 13:25 UTC, MiljkovicVeljko approved these changes

2020-09-29 13:29 UTC, mkovacevicExecom approved these changes

2020-09-29 13:41 UTC, aberonja requested changes

2020-09-29 13:41 UTC, aberonja commented on client-app/src/app/core/models/order.ts
> +import { IMeal } from '../models/meal';
/n

2020-09-29 13:41 UTC, aberonja commented on client-app/src/app/pages/home/header/header.component.ts
>          this.userService.fetchCustomerData(claims.email, claims.picture).subscribe(
Shouldn't this be dispatch as well?

2020-09-29 13:41 UTC, aberonja commented on client-app/src/app/pages/my-account/account-info/account-info.component.html
> +    <span>{{ (customer$ | async).balance | currencyFormat }}</span>
You can have one async on the top. Do some research, you'll find it quickly. :)

2020-09-29 13:41 UTC, aberonja commented on client-app/src/app/shared/mock/user.mock.ts
> +import { ICustomer } from '@core/models/customer';
/n

2020-09-30 06:38 UTC, aberonja commented on client-app/src/app/pages/home/header/header.component.ts
>          this.userService.fetchCustomerData(claims.email, claims.picture).subscribe(
Leave a @todo so you can implement dispatch once you add effects.

2020-09-30 06:40 UTC, aberonja approved these changes

2020-09-30 06:46 UTC, merged