tab UI done
execom-eu/exebite pull request #194
Opened 2020-09-29 14:48 UTC by MiljkovicVeljko

2020-09-29 21:22 UTC, MiljkovicVeljko commented on client-app/src/app/app.module.ts
> +import { CarouselComponent } from './shared/components/carousel/carousel.component';
I will replace ./shared with @shared (self-review)

2020-09-29 21:22 UTC, MiljkovicVeljko commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.html
> +<div class="card shadow pb-5 mb-5" *ngIf="carouselType === 'restaurant'">
question for reviewers: in your opinion, this will be done in separate html files, in one file as I do with ngIf, or some other way? (self-review)

2020-09-29 21:32 UTC, MiljkovicVeljko commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.scss
>      scrollbar-color: $color-primary $color-grey-dark-1;
$color-primary is old, it may have sneaked in by merging... will be removed (self-review)

2020-09-29 21:32 UTC, MiljkovicVeljko commented on client-app/src/app/shared/mock/foodTypes.mock.ts
> +export const FOOD_TYPES = [
This part will be changed when we connect back to front, in some of the next PR I guess (self-review)

2020-09-29 21:33 UTC, MiljkovicVeljko commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.html
> +    [ngClass]="{ Dessert: 'dessert', 'Traditional cuisine': 'traditional', Vegan: 'vegan' }[item.name]"
This could be shorter and more efficient, any suggestion? (self-review)

2020-09-29 21:42 UTC, MiljkovicVeljko commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.ts
> +      this.item.name === 'Dessert' ? 'cake' : this.item.name === 'Traditional cuisine' ? 'pot' : 'broccoli';
a better approach for this? (self-review)

2020-09-30 06:22 UTC, mkovacevicExecom commented on client-app/src/app/shared/components/tabs/tabs.component.ts
> +    this.receiveTab = tabName;
activeTab  is a more intuitive name

2020-09-30 06:24 UTC, mkovacevicExecom commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.ts
> +  public setColorAndIcon(foodTypeName) {
maybe you should have one method which will set icoName and icoColor?

2020-09-30 06:24 UTC, mkovacevicExecom commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.ts
> +  public setColorAndIcon(foodTypeName) {
Also, what about if we add a new food type?

2020-09-30 06:26 UTC, mkovacevicExecom commented on client-app/src/app/shared/components/carousel/carousel.component.ts
> +  @Input() carouselList: any = null;
If you don't know the type, please add comment // @TODO change type

2020-09-30 06:28 UTC, mkovacevicExecom commented on client-app/src/app/pages/restaurants-overview/restaurants-overview.component.html
> +<app-carousel *ngIf="activeTab === 'foodType'" [carouselList]="foodTypes" [carouselType]="activeTab"></app-carousel>
maybe you don't need two app-carousel selectors, you can handle it by one depending on activeTab?

2020-09-30 06:31 UTC, mkovacevicExecom commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.html
> +<div class="card shadow pb-5 mb-5" *ngIf="carouselType === 'restaurant'">
maybe you can have a generic component that will handle meal-card header depending on type?

2020-09-30 06:31 UTC, mkovacevicExecom commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.html
> +<div class="card shadow pb-5 mb-5" *ngIf="carouselType === 'restaurant'">
In that case, the header should be a separate component

2020-09-30 08:00 UTC, abericExecom approved these changes

2020-09-30 08:40 UTC, mkovacevicExecom commented on client-app/src/app/shared/mock/foodTypes.mock.ts
> +    color: '#fb9c4b',
I think we won't get color and icon property from backend, am I right? Because this mock represents data which we will get from the backend.

2020-09-30 14:17 UTC, mkovacevicExecom approved these changes

2020-10-01 06:52 UTC, aberonja requested changes

2020-10-01 06:52 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.html
> +    [style.background-color]="item.color"
Inline css?

2020-10-01 06:52 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.html
> +        *ngIf="offer"
Could this be one if?

2020-10-01 06:52 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.ts
> +import { FOOD_ITEMS } from '@shared/mock/foodItems.mock';
\n

2020-10-01 06:52 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/restaurants-overview.component.ts
> +    this.setCurrentList = event === RESTAURANTS_TAB.RESTAURANTS ? RESTAURANTS : FOOD_TYPES;
Let's call it `tab` instead of event.

2020-10-01 09:35 UTC, MiljkovicVeljko commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.html
> +    [style.background-color]="item.color"
refactor: [ngStyle]="{'background-color' : item.color}"

2020-10-01 09:35 UTC, MiljkovicVeljko commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-card.component.html
> +        *ngIf="offer"
refactor: *ngIf="offer && carouselType === 'restaurant'"

2020-10-01 11:28 UTC, aberonja approved these changes

2020-10-01 11:33 UTC, merged