notifications
execom-eu/exebite pull request #196
Opened 2020-09-30 13:34 UTC by bjokic

2020-10-01 07:16 UTC, sserbula commented on Exebite.API/Authorization/AuthorizationOptionsExtensions.cs
> +                createAccess: new List<string> { Roles.Admin, Roles.Desk },
Do we need all of this policies if we only have query method for notifications?

2020-10-01 07:19 UTC, sserbula commented on Exebite.DataAccess/DataAccessMappingProfile.cs
> +            CreateMap<NotificationEntity, Notification>();
If this 2 classes are identical and you don't need additional mappings there is no need for this line

2020-10-01 07:19 UTC, sserbula commented on Exebite.DataAccess/Entities/NotificationEntity.cs
> +        public string NotificationType { get; set; }
Maybe we could use int for type?

2020-10-01 07:20 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/Model/NotificationQueryModel.cs
> +        [JsonConverter(typeof(StringEnumConverter))]
We have this in global config

2020-10-01 07:22 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/NotificationQueryRepository.cs
> +                    var results = query.ToList();
This line isn't necessary, it is just a hit on performance

2020-10-01 07:22 UTC, sserbula commented on Exebite.DtoModels/Notification/NotificationQueryDto.cs
> +        [JsonConverter(typeof(StringEnumConverter))]
We have this in global config

2020-10-01 08:28 UTC, sserbula requested changes
Please address the comments

2020-10-02 06:13 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/NotificationCommandRepository.cs
> +                        CustomerId = entity.CustomerId,
`CustomerId` is sent from FE, so we should check if he exists in DB

2020-10-02 11:54 UTC, nikolicdusan requested changes

2020-10-02 11:54 UTC, nikolicdusan commented on Exebite.API/Controllers/CustomerReactionToMealController.cs
>      [Authorize]
This is redundant if all actions are protected

2020-10-09 12:48 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/NotificationCommandRepository.cs
> +                    else
There is no need for `else` part and instead of `throw new ArgumentException` use `return new Left<Error, bool>`

2020-10-09 12:55 UTC, sserbula commented on Exebite.API/Controllers/PaymentController.cs
> +                if (notificationInsertModel != null && notificationInsertModel.AmountBalance < 0)
```
if (notificationInsertModel?.AmountBalance < 0){
   ...
}
```

2020-10-09 12:57 UTC, sserbula commented on Exebite.API/Startup.cs
> +            app.Use(async (context, next) => // Accessing the IHubContext within the middleware pipeline
Maybe we could place comment above, it would be more readable?

2020-10-09 12:58 UTC, sserbula commented on Exebite.Business/NotificationService/NotificationHubService.cs
> +            if (Context?.User?.Identity?.Name != null)
`!String.IsNullOrEmpty(Context?.User?.Identity?.Name)`

2020-10-09 12:58 UTC, sserbula commented on Exebite.Business/NotificationService/NotificationHubService.cs
> +            if (Context?.User?.Identity?.Name != null)
`!String.IsNullOrEmpty(Context?.User?.Identity?.Name)`

2020-10-09 13:00 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/NotificationCommandRepository.cs
> +                        return new Right<Error, bool>(true);
If in both cases we return `bool` value, this `return` line isn't needed

2020-10-09 13:04 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/NotificationCommandRepository.cs
> +                var notification = notificationConstants.Replace(nameof(ReplacePartOfNotification.RestaurantName), restaurantName);
There is no need for `notification`.

`return notificationConstants.Replace(nameof(ReplacePartOfNotification.RestaurantName), restaurantName); `

2020-10-09 13:05 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/NotificationCommandRepository.cs
> +            else
There is no need for `else`, just say `return string.Empty;`

2020-10-09 13:05 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/NotificationCommandRepository.cs
> +                return notification;
There is no need for `notification`,

`return ...`

2020-10-09 13:06 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/NotificationCommandRepository.cs
> +            {
There is no need for else, just say `return string.Empty;`

2020-10-09 13:07 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/NotificationCommandRepository.cs
> +            else
There is no need for else, just say `return string.Empty;`

2020-10-09 13:08 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/NotificationCommandRepository.cs
> +        public string ReturnPaymentNotification(string amountBalance)
This method is almost identical as `ReturnRestaurantNotification`, maybe write one method with arguments?

2020-10-09 13:08 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/NotificationCommandRepository.cs
> +                    var payment = context.Payment.Where(x => x.Id == paymentId).FirstOrDefault();
`context.Payment.Find(paymentId)`

2020-10-09 13:10 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/NotificationCommandRepository.cs
> +                        var customer = context.Customer.Where(x => x.Id == payment.CustomerId).FirstOrDefault();
Payment has information about `customer`, `payment.Customer`

2020-10-09 13:10 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/NotificationCommandRepository.cs
> +                    var payment = context.Payment.Where(x => x.Id == paymentId).FirstOrDefault();
To include `customer` inside payment, use `context.Payment.Include(x => x.Customer)...`

2020-10-09 13:12 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/NotificationCommandRepository.cs
> +                    else
There is no need for `else` and use `return new Left<Error, bool>...`

2020-10-09 13:12 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/NotificationCommandRepository.cs
> +                throw new Exception(ex.ToString());
Use `return new Left<Error, bool>...`

2020-10-09 13:13 UTC, sserbula commented on Exebite.DomainModel/Enums/ReplacePartOfNotification.cs
> +    public enum ReplacePartOfNotification
There is no need for enum, if you want to replace string you can either use `{0}` or `{text}`, then replace it

2020-10-13 06:55 UTC, bjokic commented on Exebite.API/Authorization/AuthorizationOptionsExtensions.cs
> +                createAccess: new List<string> { Roles.Admin, Roles.Desk },
I think it should. Apart from the query method we also have a delete method.

2020-10-13 06:58 UTC, sserbula commented on Exebite.API/Authorization/AuthorizationOptionsExtensions.cs
> +                createAccess: new List<string> { Roles.Admin, Roles.Desk },
So we should only have readAccess and deleteAcces? Create and update isn't used inside controller?

2020-10-13 12:42 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/Model/NotificationQueryModel.cs
> +        public long? CustomerId { get; set; }
Are we sure that we want this to be nullable? If we don't get any `customerId` from FE, we will return all notifications to current customer, so basically he can see notifications from other customers as well.

2020-10-13 12:43 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/Model/NotificationUpdateModel.cs
> +        public long CusotmerId { get; set; }
Rename this to `CustomerId`

2020-10-13 12:45 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/NotificationCommandRepository.cs
> +                    if (customer != null)
If we are not using `customer` object in any business logic, we can only check if he exists `context.Customer.Any(c => c.CustomerId == entity.CustomerId)`

2020-10-13 12:49 UTC, sserbula requested changes
Please review comments

2020-10-14 08:46 UTC, sserbula commented on Exebite.DataAccess/Repositories/NotificationRepository/NotificationQueryRepository.cs
> +                        Read = x.Customer.LastNotification != null && x.Customer.LastNotification > x.Created ? true : false
This could be simplified like this `x.Customer?.LastNotification.Date > x.Created.Date`

2020-10-14 08:47 UTC, sserbula requested changes
Please address comments

2020-10-14 12:59 UTC, sserbula approved these changes

2020-10-15 06:12 UTC, nikolicdusan approved these changes

2020-10-15 06:15 UTC, merged