Select dropdown bug fix
execom-eu/exebite pull request #198
Opened 2020-10-01 11:30 UTC by abericExecom

2020-10-01 11:43 UTC, MiljkovicVeljko approved these changes

2020-10-01 12:52 UTC, mkovacevicExecom approved these changes

2020-10-01 13:53 UTC, aberonja requested changes

2020-10-01 13:53 UTC, aberonja commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.html
> +    class="item-selector-item d-flex align-items-center px-4"
Reorder.

2020-10-01 13:53 UTC, aberonja commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.html
> +    <span [class.item-selector-location-text]="isLocationSelector" class="mx-2 item-selector-text">{{
Reorder [class] and classes.

2020-10-01 13:53 UTC, aberonja commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.html
> +    class="position-absolute select-dropdown-container"
Reorder.

2020-10-01 13:53 UTC, aberonja commented on client-app/src/app/shared/components/select-dropdown/select-dropdown.component.html
> +        <span [class.item-selector-location-text]="isLocationSelector" class="mr-auto item-selector-text pt-4">{{
Reorder classes.

2020-10-02 05:44 UTC, aberonja approved these changes

2020-10-02 06:30 UTC, merged