Fix mocks
execom-eu/exebite pull request #199
Opened 2020-10-01 14:58 UTC by MiljkovicVeljko

Resolving conflicts with mock data.
also, there is a small change with the dropdown arrow

2020-10-02 05:48 UTC, aberonja requested changes

2020-10-02 05:48 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-item/meal-item.component.html
> +        <img [ngClass]="expanded ? 'on' : 'off'" alt="caret down" src="assets/images/right-arrow.svg" />
This can be done with only one class. If you add `on` then the arrow should be transformed.

2020-10-02 05:48 UTC, aberonja commented on client-app/src/app/pages/restaurants-overview/meal-card/meal-item/meal-item.component.scss
> +}
`off` is not necessary.

2020-10-02 05:48 UTC, aberonja commented on client-app/src/app/shared/mock/food-types.mock.ts
> +    color: '#fb9c4b',
Will you get this from the backend? 😕

2020-10-07 14:13 UTC, MiljkovicVeljko commented on client-app/src/app/shared/mock/food-types.mock.ts
> +    color: '#fb9c4b',
Currently, we don't have info about food types from backend (on backend we have enum with types name but we don't send it to front). So, deal is to keep it like setup on front for now.

2020-10-08 05:47 UTC, aberonja approved these changes

2020-10-08 07:42 UTC, BraneOpacic21 approved these changes

2020-10-08 07:44 UTC, merged