Like comment option
execom-eu/exebite pull request #200
Opened 2020-10-02 05:56 UTC by sserbula

2020-10-02 11:22 UTC, nikolicdusan requested changes
Please address the review comments

2020-10-02 11:22 UTC, nikolicdusan commented on Exebite.DataAccess/Repositories/CommentRepository/CommentCommandRepository.cs
> +                    return new Left<Error, bool>(new RecordNotFound(nameof(entity)));
```suggestion
                    var comment = context.Comment.Find(entity.MealId, entity.CommentId);
                    if (comment != null && comment.CustomerId == entity.CustomerId)
                    {
                        var reaction = context.ReactionToComment.SingleOrDefault(rc => rc.MealId == comment.MealId
                                                        && rc.CommentId == comment.CommentId
                                                        && rc.CustomerId == entity.CustomerId);
                        if (reaction != null)
                        {
                            context.ReactionToComment.Remove(reaction);
                            context.SaveChanges();

                            return new Right<Error, bool>(true);
                        }
                    }

                    return new Left<Error, bool>(new RecordNotFound(nameof(entity)));
```

2020-10-02 11:22 UTC, nikolicdusan commented on Exebite.DataAccess/Repositories/CommentRepository/CommentCommandRepository.cs
> +                            ReactionId = (long)Reaction.Like
Every reaction is `Reaction.Like`?

2020-10-02 11:22 UTC, nikolicdusan commented on Exebite.API/Controllers/CommentsController.cs
> +        [HttpDelete("reaction")]
It's common to provide the `{id}` of the record that should be deleted.

```suggestion
        [HttpDelete("reaction/{reactionId}")]
```

2020-10-02 11:22 UTC, nikolicdusan commented on Test/Exebite.DataAccess.Test/CommentReactionRepositoryTest.cs
> +}
Let's not push empty classes with no use whatsoever.

2020-10-02 11:40 UTC, sserbula commented on Exebite.DataAccess/Repositories/CommentRepository/CommentCommandRepository.cs
> +                            ReactionId = (long)Reaction.Like
We can only like comments and we already had table `Reaction` with `Like` entity, so I used it. When customer remove like, I remove entity from `ReactionToComment` table

2020-10-02 12:09 UTC, nikolicdusan requested changes
Review comments

2020-10-08 12:36 UTC, nikolicdusan approved these changes
Looks good

2020-10-08 12:39 UTC, merged