#171 delete meal comment
execom-eu/exebite pull request #201
Opened 2020-10-02 09:21 UTC by sserbula

2020-10-02 10:33 UTC, nikolicdusan requested changes
Please address comments and apply neccessary modifications

2020-10-02 10:33 UTC, nikolicdusan commented on Exebite.DataAccess/Repositories/CommentRepository/CommentCommandRepository.cs
> +                    var comment = context.Comment.SingleOrDefault(c => c.MealId == commentDto.MealId && c.CommentId == commentId && c.CustomerId == commentDto.CustomerId);
A `CommentEntity` record is uniquely identified by `MealId` and `CommentId`. The `CustomerId` filter in this query is redundant.

2020-10-02 10:33 UTC, nikolicdusan commented on Exebite.API/Controllers/CommentsController.cs
> +        public IActionResult Delete(int id, [FromBody] DeleteCommentDto comment) =>
Usually the `{id}` route property is enough to find the record that should be deleted. Since our `CommentEntity` has a composite primary key, the delete endpoint could have looked like following:

```suggestion
        [HttpDelete("{commentId}/meal/{mealId}")]
        [Authorize(Policy = nameof(AccessPolicy.DeleteMealAccessPolicy))]
        public IActionResult Delete(int commentId, long mealId) =>
```

2020-10-02 10:33 UTC, nikolicdusan commented on Exebite.DataAccess/Repositories/CommentRepository/ICommentCommandRepository.cs
> +        Either<Error, bool> Delete(int commentId, DeleteCommentDto comment);
Consequently, if we were to modify the delete comment endpoint route, this method would look like following:

```suggestion
        Either<Error, bool> Delete(int commentId, long mealId);
```

2020-10-02 10:33 UTC, nikolicdusan commented on Exebite.DataAccess/Repositories/CommentRepository/CommentCommandRepository.cs
> +                    var comment = context.Comment.SingleOrDefault(c => c.MealId == commentDto.MealId && c.CommentId == commentId && c.CustomerId == commentDto.CustomerId);
You can also use following `DbContext.Find` method:

```suggestion
                    var comment = context.Comment.Find(mealId, commentId);
```

**Note** that the members of the composite key need to be provided in the proper order to the `DbContext.Find` method.

2020-10-02 11:31 UTC, sserbula commented on Exebite.DataAccess/Repositories/CommentRepository/CommentCommandRepository.cs
> +                    var comment = context.Comment.SingleOrDefault(c => c.MealId == commentDto.MealId && c.CommentId == commentId && c.CustomerId == commentDto.CustomerId);
Customer can only delete his own comment, so I am doing this to be sure that specified comment was created by this customer

2020-10-08 12:34 UTC, nikolicdusan approved these changes
Looks good

2020-10-08 12:45 UTC, merged