Refactor=sheet fetch
execom-eu/exebite pull request #206
Opened 2020-10-06 12:19 UTC by sserbula

2020-10-08 12:32 UTC, nikolicdusan requested changes
Please review comments

2020-10-08 12:59 UTC, sserbula commented on Exebite.Common/Extensions/StringExtensions.cs
> +                "" => throw new ArgumentException($"{nameof(input)} cannot be empty", nameof(input)),
`string.IsNullOrEmpty()` returns boolean value and I am using `string` inside `switch`.
When I tried using `string.Empty` I got error `A Constant value is expected`

2020-10-08 13:10 UTC, sserbula commented on Exebite.Common/Extensions/StringExtensions.cs
> +                _ => input.First().ToString().ToUpper() + input.Substring(1)
If number or symbol is the first char, nothing happens, same string is returned, e.g. `22s` => `22s`

2020-10-14 10:01 UTC, bjokic commented on Exebite.Common/Constants/SheetConstants.cs
> +        public const string TOPLI_BROK_MENU_PRICE_RANGE = "!D4:4";
Correct the constant name

2020-10-14 10:12 UTC, bjokic requested changes
Please review the comment.

2020-10-14 12:13 UTC, bjokic approved these changes
Looks good

2020-10-14 12:19 UTC, nikolicdusan approved these changes

2020-10-14 12:20 UTC, merged