Demo preparation
execom-eu/exebite pull request #213
Opened 2020-10-09 14:31 UTC by sserbula

Contains #211

2020-10-13 06:24 UTC, bjokic commented on Exebite.DataAccess/Repositories/CommentRepository/CommentCommandRepository.cs
> +                            ReactionId = context.Reaction.Single(x => x.Description.Equals(Enum.GetName(typeof(ReactionType), ReactionType.Like))).Id
Instead of (Enum.GetName(typeof(ReactionType), ReactionType.Like)) we can use (nameof(ReactionType.Like))

2020-10-14 12:09 UTC, bjokic commented on Exebite.DataAccess/Repositories/MealRepository/MealCommandRepository.cs
Would it maybe be better if we wrote this method as asynchronous?

2020-10-14 12:28 UTC, bjokic requested changes
Please review the comments.

2020-10-21 07:21 UTC, nikolicdusan approved these changes
Looks good

2020-10-21 07:23 UTC, bjokic approved these changes

2020-10-21 07:23 UTC, nikolicdusan reviewed
Looks good

2020-10-21 07:23 UTC, merged