ui fixs meal-item , header , order-item  ,responsive
execom-eu/exebite pull request #231
Opened 2020-10-21 08:20 UTC by bulic

2020-10-21 08:33 UTC, abericExecom approved these changes

2020-10-22 07:21 UTC, BraneOpacic21 requested changes

2020-10-22 07:21 UTC, BraneOpacic21 commented on client-app/src/app/pages/my-order/order-item/order-item.component.html
> +        <img class="mr-3 cursor-pointer" alt="comment" src="assets/images/Dislike.svg" (click)="dislike()" />
Just to improve readability, lets use this order of decorating our HTML code:
1. Structural directives (e.g. `*ngIf`)
2. Methods (e.g. `*(click)="like()"`)
3. Other directives (e.g. `*colorOnHover`)
4. CSS classes
5. Other stuff
6. Alt text

2020-10-22 08:34 UTC, BraneOpacic21 approved these changes
If you are not waiting for other PRs to be merged before yours, you can merge this one @bulic

2020-10-22 08:36 UTC, merged